### ISSUE TITLE
转caffe时key error

### ISSUE THREAD

**Issue by jiejiangd** [mahxn0/Yolov5-Hisi3559a-Train#1]
您好，我是用的yolov5v6.0转的，然后报了这个错，想请问一下这类问题应该如何找原因哦
Traceback (most recent call last):
  File "convertCaffe.py", line 162, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 83, in convertToCaffe
    layer = converter_fn(node, graph, err)
  File "/home/hyj/PROJECTS/Yolov5-Hisi3559a-Train-master/yolov5_onnx2caffe/onnx2caffe/_operators.py", line 134, in _convert_sigmoid
    graph.channel_dims[output_name] = graph.channel_dims[input_name]
KeyError: '343'

**Comment by SlamDunk-ycw** [comment]
你好，你找到原因了嘛？ 可以分享一下嘛
